# Autogenerated using ProtoBuf.jl v1.1.1 on 2025-04-15T13:34:17.662
# original file: /var/folders/z8/3_xmt_5d7vs6hdclc083pvlh0000gn/T/jl_SWx4UK/opentelemetry-proto-1.5.0/opentelemetry/proto/collector/profiles/v1development/profiles_service.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ExportProfilesServiceRequest, ExportProfilesPartialSuccess
export ExportProfilesServiceResponse, ProfilesService


struct ExportProfilesServiceRequest
    resource_profiles::Vector{opentelemetry.proto.profiles.v1development.ResourceProfiles}
end
PB.default_values(::Type{ExportProfilesServiceRequest}) = (;resource_profiles = Vector{opentelemetry.proto.profiles.v1development.ResourceProfiles}())
PB.field_numbers(::Type{ExportProfilesServiceRequest}) = (;resource_profiles = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExportProfilesServiceRequest})
    resource_profiles = PB.BufferedVector{opentelemetry.proto.profiles.v1development.ResourceProfiles}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, resource_profiles)
        else
            PB.skip(d, wire_type)
        end
    end
    return ExportProfilesServiceRequest(resource_profiles[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExportProfilesServiceRequest)
    initpos = position(e.io)
    !isempty(x.resource_profiles) && PB.encode(e, 1, x.resource_profiles)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExportProfilesServiceRequest)
    encoded_size = 0
    !isempty(x.resource_profiles) && (encoded_size += PB._encoded_size(x.resource_profiles, 1))
    return encoded_size
end

struct ExportProfilesPartialSuccess
    rejected_profiles::Int64
    error_message::String
end
PB.default_values(::Type{ExportProfilesPartialSuccess}) = (;rejected_profiles = zero(Int64), error_message = "")
PB.field_numbers(::Type{ExportProfilesPartialSuccess}) = (;rejected_profiles = 1, error_message = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExportProfilesPartialSuccess})
    rejected_profiles = zero(Int64)
    error_message = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            rejected_profiles = PB.decode(d, Int64)
        elseif field_number == 2
            error_message = PB.decode(d, String)
        else
            PB.skip(d, wire_type)
        end
    end
    return ExportProfilesPartialSuccess(rejected_profiles, error_message)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExportProfilesPartialSuccess)
    initpos = position(e.io)
    x.rejected_profiles != zero(Int64) && PB.encode(e, 1, x.rejected_profiles)
    !isempty(x.error_message) && PB.encode(e, 2, x.error_message)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExportProfilesPartialSuccess)
    encoded_size = 0
    x.rejected_profiles != zero(Int64) && (encoded_size += PB._encoded_size(x.rejected_profiles, 1))
    !isempty(x.error_message) && (encoded_size += PB._encoded_size(x.error_message, 2))
    return encoded_size
end

struct ExportProfilesServiceResponse
    partial_success::Union{Nothing,ExportProfilesPartialSuccess}
end
PB.default_values(::Type{ExportProfilesServiceResponse}) = (;partial_success = nothing)
PB.field_numbers(::Type{ExportProfilesServiceResponse}) = (;partial_success = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExportProfilesServiceResponse})
    partial_success = Ref{Union{Nothing,ExportProfilesPartialSuccess}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, partial_success)
        else
            PB.skip(d, wire_type)
        end
    end
    return ExportProfilesServiceResponse(partial_success[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExportProfilesServiceResponse)
    initpos = position(e.io)
    !isnothing(x.partial_success) && PB.encode(e, 1, x.partial_success)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExportProfilesServiceResponse)
    encoded_size = 0
    !isnothing(x.partial_success) && (encoded_size += PB._encoded_size(x.partial_success, 1))
    return encoded_size
end

# TODO: SERVICE
#    ProfilesService
