# Autogenerated using ProtoBuf.jl v1.1.1 on 2025-04-15T13:36:56.185
# original file: /var/folders/z8/3_xmt_5d7vs6hdclc083pvlh0000gn/T/jl_nzYIV2/opentelemetry-proto-1.5.0/opentelemetry/proto/profiles/v1development/profiles.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: AbstractProtoBufMessage
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Line, Sample, AttributeUnit, Mapping, AggregationTemporality, Function, Link
export Location, ValueType, Profile, ScopeProfiles, ResourceProfiles, ProfilesData


struct Line <: AbstractProtoBufMessage
    function_index::Int32
    line::Int64
    column::Int64
end
PB.default_values(::Type{Line}) = (;function_index = zero(Int32), line = zero(Int64), column = zero(Int64))
PB.field_numbers(::Type{Line}) = (;function_index = 1, line = 2, column = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Line})
    function_index = zero(Int32)
    line = zero(Int64)
    column = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            function_index = PB.decode(d, Int32)
        elseif field_number == 2
            line = PB.decode(d, Int64)
        elseif field_number == 3
            column = PB.decode(d, Int64)
        else
            PB.skip(d, wire_type)
        end
    end
    return Line(function_index, line, column)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Line)
    initpos = position(e.io)
    x.function_index != zero(Int32) && PB.encode(e, 1, x.function_index)
    x.line != zero(Int64) && PB.encode(e, 2, x.line)
    x.column != zero(Int64) && PB.encode(e, 3, x.column)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Line)
    encoded_size = 0
    x.function_index != zero(Int32) && (encoded_size += PB._encoded_size(x.function_index, 1))
    x.line != zero(Int64) && (encoded_size += PB._encoded_size(x.line, 2))
    x.column != zero(Int64) && (encoded_size += PB._encoded_size(x.column, 3))
    return encoded_size
end

struct Sample <: AbstractProtoBufMessage
    locations_start_index::Int32
    locations_length::Int32
    value::Vector{Int64}
    attribute_indices::Vector{Int32}
    link_index::Int32
    timestamps_unix_nano::Vector{UInt64}
end
PB.default_values(::Type{Sample}) = (;locations_start_index = zero(Int32), locations_length = zero(Int32), value = Vector{Int64}(), attribute_indices = Vector{Int32}(), link_index = zero(Int32), timestamps_unix_nano = Vector{UInt64}())
PB.field_numbers(::Type{Sample}) = (;locations_start_index = 1, locations_length = 2, value = 3, attribute_indices = 4, link_index = 5, timestamps_unix_nano = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Sample})
    locations_start_index = zero(Int32)
    locations_length = zero(Int32)
    value = PB.BufferedVector{Int64}()
    attribute_indices = PB.BufferedVector{Int32}()
    link_index = zero(Int32)
    timestamps_unix_nano = PB.BufferedVector{UInt64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            locations_start_index = PB.decode(d, Int32)
        elseif field_number == 2
            locations_length = PB.decode(d, Int32)
        elseif field_number == 3
            PB.decode!(d, wire_type, value)
        elseif field_number == 4
            PB.decode!(d, wire_type, attribute_indices)
        elseif field_number == 5
            link_index = PB.decode(d, Int32)
        elseif field_number == 6
            PB.decode!(d, wire_type, timestamps_unix_nano)
        else
            PB.skip(d, wire_type)
        end
    end
    return Sample(locations_start_index, locations_length, value[], attribute_indices[], link_index, timestamps_unix_nano[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Sample)
    initpos = position(e.io)
    x.locations_start_index != zero(Int32) && PB.encode(e, 1, x.locations_start_index)
    x.locations_length != zero(Int32) && PB.encode(e, 2, x.locations_length)
    !isempty(x.value) && PB.encode(e, 3, x.value)
    !isempty(x.attribute_indices) && PB.encode(e, 4, x.attribute_indices)
    x.link_index != zero(Int32) && PB.encode(e, 5, x.link_index)
    !isempty(x.timestamps_unix_nano) && PB.encode(e, 6, x.timestamps_unix_nano)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Sample)
    encoded_size = 0
    x.locations_start_index != zero(Int32) && (encoded_size += PB._encoded_size(x.locations_start_index, 1))
    x.locations_length != zero(Int32) && (encoded_size += PB._encoded_size(x.locations_length, 2))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 3))
    !isempty(x.attribute_indices) && (encoded_size += PB._encoded_size(x.attribute_indices, 4))
    x.link_index != zero(Int32) && (encoded_size += PB._encoded_size(x.link_index, 5))
    !isempty(x.timestamps_unix_nano) && (encoded_size += PB._encoded_size(x.timestamps_unix_nano, 6))
    return encoded_size
end

struct AttributeUnit <: AbstractProtoBufMessage
    attribute_key_strindex::Int32
    unit_strindex::Int32
end
PB.default_values(::Type{AttributeUnit}) = (;attribute_key_strindex = zero(Int32), unit_strindex = zero(Int32))
PB.field_numbers(::Type{AttributeUnit}) = (;attribute_key_strindex = 1, unit_strindex = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AttributeUnit})
    attribute_key_strindex = zero(Int32)
    unit_strindex = zero(Int32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            attribute_key_strindex = PB.decode(d, Int32)
        elseif field_number == 2
            unit_strindex = PB.decode(d, Int32)
        else
            PB.skip(d, wire_type)
        end
    end
    return AttributeUnit(attribute_key_strindex, unit_strindex)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AttributeUnit)
    initpos = position(e.io)
    x.attribute_key_strindex != zero(Int32) && PB.encode(e, 1, x.attribute_key_strindex)
    x.unit_strindex != zero(Int32) && PB.encode(e, 2, x.unit_strindex)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AttributeUnit)
    encoded_size = 0
    x.attribute_key_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.attribute_key_strindex, 1))
    x.unit_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.unit_strindex, 2))
    return encoded_size
end

struct Mapping <: AbstractProtoBufMessage
    memory_start::UInt64
    memory_limit::UInt64
    file_offset::UInt64
    filename_strindex::Int32
    attribute_indices::Vector{Int32}
    has_functions::Bool
    has_filenames::Bool
    has_line_numbers::Bool
    has_inline_frames::Bool
end
PB.default_values(::Type{Mapping}) = (;memory_start = zero(UInt64), memory_limit = zero(UInt64), file_offset = zero(UInt64), filename_strindex = zero(Int32), attribute_indices = Vector{Int32}(), has_functions = false, has_filenames = false, has_line_numbers = false, has_inline_frames = false)
PB.field_numbers(::Type{Mapping}) = (;memory_start = 1, memory_limit = 2, file_offset = 3, filename_strindex = 4, attribute_indices = 5, has_functions = 6, has_filenames = 7, has_line_numbers = 8, has_inline_frames = 9)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Mapping})
    memory_start = zero(UInt64)
    memory_limit = zero(UInt64)
    file_offset = zero(UInt64)
    filename_strindex = zero(Int32)
    attribute_indices = PB.BufferedVector{Int32}()
    has_functions = false
    has_filenames = false
    has_line_numbers = false
    has_inline_frames = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            memory_start = PB.decode(d, UInt64)
        elseif field_number == 2
            memory_limit = PB.decode(d, UInt64)
        elseif field_number == 3
            file_offset = PB.decode(d, UInt64)
        elseif field_number == 4
            filename_strindex = PB.decode(d, Int32)
        elseif field_number == 5
            PB.decode!(d, wire_type, attribute_indices)
        elseif field_number == 6
            has_functions = PB.decode(d, Bool)
        elseif field_number == 7
            has_filenames = PB.decode(d, Bool)
        elseif field_number == 8
            has_line_numbers = PB.decode(d, Bool)
        elseif field_number == 9
            has_inline_frames = PB.decode(d, Bool)
        else
            PB.skip(d, wire_type)
        end
    end
    return Mapping(memory_start, memory_limit, file_offset, filename_strindex, attribute_indices[], has_functions, has_filenames, has_line_numbers, has_inline_frames)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Mapping)
    initpos = position(e.io)
    x.memory_start != zero(UInt64) && PB.encode(e, 1, x.memory_start)
    x.memory_limit != zero(UInt64) && PB.encode(e, 2, x.memory_limit)
    x.file_offset != zero(UInt64) && PB.encode(e, 3, x.file_offset)
    x.filename_strindex != zero(Int32) && PB.encode(e, 4, x.filename_strindex)
    !isempty(x.attribute_indices) && PB.encode(e, 5, x.attribute_indices)
    x.has_functions != false && PB.encode(e, 6, x.has_functions)
    x.has_filenames != false && PB.encode(e, 7, x.has_filenames)
    x.has_line_numbers != false && PB.encode(e, 8, x.has_line_numbers)
    x.has_inline_frames != false && PB.encode(e, 9, x.has_inline_frames)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Mapping)
    encoded_size = 0
    x.memory_start != zero(UInt64) && (encoded_size += PB._encoded_size(x.memory_start, 1))
    x.memory_limit != zero(UInt64) && (encoded_size += PB._encoded_size(x.memory_limit, 2))
    x.file_offset != zero(UInt64) && (encoded_size += PB._encoded_size(x.file_offset, 3))
    x.filename_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.filename_strindex, 4))
    !isempty(x.attribute_indices) && (encoded_size += PB._encoded_size(x.attribute_indices, 5))
    x.has_functions != false && (encoded_size += PB._encoded_size(x.has_functions, 6))
    x.has_filenames != false && (encoded_size += PB._encoded_size(x.has_filenames, 7))
    x.has_line_numbers != false && (encoded_size += PB._encoded_size(x.has_line_numbers, 8))
    x.has_inline_frames != false && (encoded_size += PB._encoded_size(x.has_inline_frames, 9))
    return encoded_size
end

@enumx AggregationTemporality AGGREGATION_TEMPORALITY_UNSPECIFIED=0 AGGREGATION_TEMPORALITY_DELTA=1 AGGREGATION_TEMPORALITY_CUMULATIVE=2

struct Function <: AbstractProtoBufMessage
    name_strindex::Int32
    system_name_strindex::Int32
    filename_strindex::Int32
    start_line::Int64
end
PB.default_values(::Type{Function}) = (;name_strindex = zero(Int32), system_name_strindex = zero(Int32), filename_strindex = zero(Int32), start_line = zero(Int64))
PB.field_numbers(::Type{Function}) = (;name_strindex = 1, system_name_strindex = 2, filename_strindex = 3, start_line = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Function})
    name_strindex = zero(Int32)
    system_name_strindex = zero(Int32)
    filename_strindex = zero(Int32)
    start_line = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name_strindex = PB.decode(d, Int32)
        elseif field_number == 2
            system_name_strindex = PB.decode(d, Int32)
        elseif field_number == 3
            filename_strindex = PB.decode(d, Int32)
        elseif field_number == 4
            start_line = PB.decode(d, Int64)
        else
            PB.skip(d, wire_type)
        end
    end
    return Function(name_strindex, system_name_strindex, filename_strindex, start_line)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Function)
    initpos = position(e.io)
    x.name_strindex != zero(Int32) && PB.encode(e, 1, x.name_strindex)
    x.system_name_strindex != zero(Int32) && PB.encode(e, 2, x.system_name_strindex)
    x.filename_strindex != zero(Int32) && PB.encode(e, 3, x.filename_strindex)
    x.start_line != zero(Int64) && PB.encode(e, 4, x.start_line)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Function)
    encoded_size = 0
    x.name_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.name_strindex, 1))
    x.system_name_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.system_name_strindex, 2))
    x.filename_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.filename_strindex, 3))
    x.start_line != zero(Int64) && (encoded_size += PB._encoded_size(x.start_line, 4))
    return encoded_size
end

struct Link <: AbstractProtoBufMessage
    trace_id::Vector{UInt8}
    span_id::Vector{UInt8}
end
PB.default_values(::Type{Link}) = (;trace_id = UInt8[], span_id = UInt8[])
PB.field_numbers(::Type{Link}) = (;trace_id = 1, span_id = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Link})
    trace_id = UInt8[]
    span_id = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            trace_id = PB.decode(d, Vector{UInt8})
        elseif field_number == 2
            span_id = PB.decode(d, Vector{UInt8})
        else
            PB.skip(d, wire_type)
        end
    end
    return Link(trace_id, span_id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Link)
    initpos = position(e.io)
    !isempty(x.trace_id) && PB.encode(e, 1, x.trace_id)
    !isempty(x.span_id) && PB.encode(e, 2, x.span_id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Link)
    encoded_size = 0
    !isempty(x.trace_id) && (encoded_size += PB._encoded_size(x.trace_id, 1))
    !isempty(x.span_id) && (encoded_size += PB._encoded_size(x.span_id, 2))
    return encoded_size
end

struct Location <: AbstractProtoBufMessage
    mapping_index::Int32
    address::UInt64
    line::Vector{Line}
    is_folded::Bool
    attribute_indices::Vector{Int32}
end
PB.default_values(::Type{Location}) = (;mapping_index = zero(Int32), address = zero(UInt64), line = Vector{Line}(), is_folded = false, attribute_indices = Vector{Int32}())
PB.field_numbers(::Type{Location}) = (;mapping_index = 1, address = 2, line = 3, is_folded = 4, attribute_indices = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Location})
    mapping_index = zero(Int32)
    address = zero(UInt64)
    line = PB.BufferedVector{Line}()
    is_folded = false
    attribute_indices = PB.BufferedVector{Int32}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mapping_index = PB.decode(d, Int32)
        elseif field_number == 2
            address = PB.decode(d, UInt64)
        elseif field_number == 3
            PB.decode!(d, line)
        elseif field_number == 4
            is_folded = PB.decode(d, Bool)
        elseif field_number == 5
            PB.decode!(d, wire_type, attribute_indices)
        else
            PB.skip(d, wire_type)
        end
    end
    return Location(mapping_index, address, line[], is_folded, attribute_indices[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Location)
    initpos = position(e.io)
    x.mapping_index != zero(Int32) && PB.encode(e, 1, x.mapping_index)
    x.address != zero(UInt64) && PB.encode(e, 2, x.address)
    !isempty(x.line) && PB.encode(e, 3, x.line)
    x.is_folded != false && PB.encode(e, 4, x.is_folded)
    !isempty(x.attribute_indices) && PB.encode(e, 5, x.attribute_indices)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Location)
    encoded_size = 0
    x.mapping_index != zero(Int32) && (encoded_size += PB._encoded_size(x.mapping_index, 1))
    x.address != zero(UInt64) && (encoded_size += PB._encoded_size(x.address, 2))
    !isempty(x.line) && (encoded_size += PB._encoded_size(x.line, 3))
    x.is_folded != false && (encoded_size += PB._encoded_size(x.is_folded, 4))
    !isempty(x.attribute_indices) && (encoded_size += PB._encoded_size(x.attribute_indices, 5))
    return encoded_size
end

struct ValueType <: AbstractProtoBufMessage
    type_strindex::Int32
    unit_strindex::Int32
    aggregation_temporality::AggregationTemporality.T
end
PB.default_values(::Type{ValueType}) = (;type_strindex = zero(Int32), unit_strindex = zero(Int32), aggregation_temporality = AggregationTemporality.AGGREGATION_TEMPORALITY_UNSPECIFIED)
PB.field_numbers(::Type{ValueType}) = (;type_strindex = 1, unit_strindex = 2, aggregation_temporality = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ValueType})
    type_strindex = zero(Int32)
    unit_strindex = zero(Int32)
    aggregation_temporality = AggregationTemporality.AGGREGATION_TEMPORALITY_UNSPECIFIED
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            type_strindex = PB.decode(d, Int32)
        elseif field_number == 2
            unit_strindex = PB.decode(d, Int32)
        elseif field_number == 3
            aggregation_temporality = PB.decode(d, AggregationTemporality.T)
        else
            PB.skip(d, wire_type)
        end
    end
    return ValueType(type_strindex, unit_strindex, aggregation_temporality)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ValueType)
    initpos = position(e.io)
    x.type_strindex != zero(Int32) && PB.encode(e, 1, x.type_strindex)
    x.unit_strindex != zero(Int32) && PB.encode(e, 2, x.unit_strindex)
    x.aggregation_temporality != AggregationTemporality.AGGREGATION_TEMPORALITY_UNSPECIFIED && PB.encode(e, 3, x.aggregation_temporality)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ValueType)
    encoded_size = 0
    x.type_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.type_strindex, 1))
    x.unit_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.unit_strindex, 2))
    x.aggregation_temporality != AggregationTemporality.AGGREGATION_TEMPORALITY_UNSPECIFIED && (encoded_size += PB._encoded_size(x.aggregation_temporality, 3))
    return encoded_size
end

struct Profile <: AbstractProtoBufMessage
    sample_type::Vector{ValueType}
    sample::Vector{Sample}
    mapping_table::Vector{Mapping}
    location_table::Vector{Location}
    location_indices::Vector{Int32}
    function_table::Vector{Function}
    attribute_table::Vector{opentelemetry.proto.common.v1.KeyValue}
    attribute_units::Vector{AttributeUnit}
    link_table::Vector{Link}
    string_table::Vector{String}
    time_nanos::Int64
    duration_nanos::Int64
    period_type::Union{Nothing,ValueType}
    period::Int64
    comment_strindices::Vector{Int32}
    default_sample_type_strindex::Int32
    profile_id::Vector{UInt8}
    dropped_attributes_count::UInt32
    original_payload_format::String
    original_payload::Vector{UInt8}
    attribute_indices::Vector{Int32}
end
PB.default_values(::Type{Profile}) = (;sample_type = Vector{ValueType}(), sample = Vector{Sample}(), mapping_table = Vector{Mapping}(), location_table = Vector{Location}(), location_indices = Vector{Int32}(), function_table = Vector{Function}(), attribute_table = Vector{opentelemetry.proto.common.v1.KeyValue}(), attribute_units = Vector{AttributeUnit}(), link_table = Vector{Link}(), string_table = Vector{String}(), time_nanos = zero(Int64), duration_nanos = zero(Int64), period_type = nothing, period = zero(Int64), comment_strindices = Vector{Int32}(), default_sample_type_strindex = zero(Int32), profile_id = UInt8[], dropped_attributes_count = zero(UInt32), original_payload_format = "", original_payload = UInt8[], attribute_indices = Vector{Int32}())
PB.field_numbers(::Type{Profile}) = (;sample_type = 1, sample = 2, mapping_table = 3, location_table = 4, location_indices = 5, function_table = 6, attribute_table = 7, attribute_units = 8, link_table = 9, string_table = 10, time_nanos = 11, duration_nanos = 12, period_type = 13, period = 14, comment_strindices = 15, default_sample_type_strindex = 16, profile_id = 17, dropped_attributes_count = 19, original_payload_format = 20, original_payload = 21, attribute_indices = 22)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Profile})
    sample_type = PB.BufferedVector{ValueType}()
    sample = PB.BufferedVector{Sample}()
    mapping_table = PB.BufferedVector{Mapping}()
    location_table = PB.BufferedVector{Location}()
    location_indices = PB.BufferedVector{Int32}()
    function_table = PB.BufferedVector{Function}()
    attribute_table = PB.BufferedVector{opentelemetry.proto.common.v1.KeyValue}()
    attribute_units = PB.BufferedVector{AttributeUnit}()
    link_table = PB.BufferedVector{Link}()
    string_table = PB.BufferedVector{String}()
    time_nanos = zero(Int64)
    duration_nanos = zero(Int64)
    period_type = Ref{Union{Nothing,ValueType}}(nothing)
    period = zero(Int64)
    comment_strindices = PB.BufferedVector{Int32}()
    default_sample_type_strindex = zero(Int32)
    profile_id = UInt8[]
    dropped_attributes_count = zero(UInt32)
    original_payload_format = ""
    original_payload = UInt8[]
    attribute_indices = PB.BufferedVector{Int32}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, sample_type)
        elseif field_number == 2
            PB.decode!(d, sample)
        elseif field_number == 3
            PB.decode!(d, mapping_table)
        elseif field_number == 4
            PB.decode!(d, location_table)
        elseif field_number == 5
            PB.decode!(d, wire_type, location_indices)
        elseif field_number == 6
            PB.decode!(d, function_table)
        elseif field_number == 7
            PB.decode!(d, attribute_table)
        elseif field_number == 8
            PB.decode!(d, attribute_units)
        elseif field_number == 9
            PB.decode!(d, link_table)
        elseif field_number == 10
            PB.decode!(d, string_table)
        elseif field_number == 11
            time_nanos = PB.decode(d, Int64)
        elseif field_number == 12
            duration_nanos = PB.decode(d, Int64)
        elseif field_number == 13
            PB.decode!(d, period_type)
        elseif field_number == 14
            period = PB.decode(d, Int64)
        elseif field_number == 15
            PB.decode!(d, wire_type, comment_strindices)
        elseif field_number == 16
            default_sample_type_strindex = PB.decode(d, Int32)
        elseif field_number == 17
            profile_id = PB.decode(d, Vector{UInt8})
        elseif field_number == 19
            dropped_attributes_count = PB.decode(d, UInt32)
        elseif field_number == 20
            original_payload_format = PB.decode(d, String)
        elseif field_number == 21
            original_payload = PB.decode(d, Vector{UInt8})
        elseif field_number == 22
            PB.decode!(d, wire_type, attribute_indices)
        else
            PB.skip(d, wire_type)
        end
    end
    return Profile(sample_type[], sample[], mapping_table[], location_table[], location_indices[], function_table[], attribute_table[], attribute_units[], link_table[], string_table[], time_nanos, duration_nanos, period_type[], period, comment_strindices[], default_sample_type_strindex, profile_id, dropped_attributes_count, original_payload_format, original_payload, attribute_indices[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Profile)
    initpos = position(e.io)
    !isempty(x.sample_type) && PB.encode(e, 1, x.sample_type)
    !isempty(x.sample) && PB.encode(e, 2, x.sample)
    !isempty(x.mapping_table) && PB.encode(e, 3, x.mapping_table)
    !isempty(x.location_table) && PB.encode(e, 4, x.location_table)
    !isempty(x.location_indices) && PB.encode(e, 5, x.location_indices)
    !isempty(x.function_table) && PB.encode(e, 6, x.function_table)
    !isempty(x.attribute_table) && PB.encode(e, 7, x.attribute_table)
    !isempty(x.attribute_units) && PB.encode(e, 8, x.attribute_units)
    !isempty(x.link_table) && PB.encode(e, 9, x.link_table)
    !isempty(x.string_table) && PB.encode(e, 10, x.string_table)
    x.time_nanos != zero(Int64) && PB.encode(e, 11, x.time_nanos)
    x.duration_nanos != zero(Int64) && PB.encode(e, 12, x.duration_nanos)
    !isnothing(x.period_type) && PB.encode(e, 13, x.period_type)
    x.period != zero(Int64) && PB.encode(e, 14, x.period)
    !isempty(x.comment_strindices) && PB.encode(e, 15, x.comment_strindices)
    x.default_sample_type_strindex != zero(Int32) && PB.encode(e, 16, x.default_sample_type_strindex)
    !isempty(x.profile_id) && PB.encode(e, 17, x.profile_id)
    x.dropped_attributes_count != zero(UInt32) && PB.encode(e, 19, x.dropped_attributes_count)
    !isempty(x.original_payload_format) && PB.encode(e, 20, x.original_payload_format)
    !isempty(x.original_payload) && PB.encode(e, 21, x.original_payload)
    !isempty(x.attribute_indices) && PB.encode(e, 22, x.attribute_indices)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Profile)
    encoded_size = 0
    !isempty(x.sample_type) && (encoded_size += PB._encoded_size(x.sample_type, 1))
    !isempty(x.sample) && (encoded_size += PB._encoded_size(x.sample, 2))
    !isempty(x.mapping_table) && (encoded_size += PB._encoded_size(x.mapping_table, 3))
    !isempty(x.location_table) && (encoded_size += PB._encoded_size(x.location_table, 4))
    !isempty(x.location_indices) && (encoded_size += PB._encoded_size(x.location_indices, 5))
    !isempty(x.function_table) && (encoded_size += PB._encoded_size(x.function_table, 6))
    !isempty(x.attribute_table) && (encoded_size += PB._encoded_size(x.attribute_table, 7))
    !isempty(x.attribute_units) && (encoded_size += PB._encoded_size(x.attribute_units, 8))
    !isempty(x.link_table) && (encoded_size += PB._encoded_size(x.link_table, 9))
    !isempty(x.string_table) && (encoded_size += PB._encoded_size(x.string_table, 10))
    x.time_nanos != zero(Int64) && (encoded_size += PB._encoded_size(x.time_nanos, 11))
    x.duration_nanos != zero(Int64) && (encoded_size += PB._encoded_size(x.duration_nanos, 12))
    !isnothing(x.period_type) && (encoded_size += PB._encoded_size(x.period_type, 13))
    x.period != zero(Int64) && (encoded_size += PB._encoded_size(x.period, 14))
    !isempty(x.comment_strindices) && (encoded_size += PB._encoded_size(x.comment_strindices, 15))
    x.default_sample_type_strindex != zero(Int32) && (encoded_size += PB._encoded_size(x.default_sample_type_strindex, 16))
    !isempty(x.profile_id) && (encoded_size += PB._encoded_size(x.profile_id, 17))
    x.dropped_attributes_count != zero(UInt32) && (encoded_size += PB._encoded_size(x.dropped_attributes_count, 19))
    !isempty(x.original_payload_format) && (encoded_size += PB._encoded_size(x.original_payload_format, 20))
    !isempty(x.original_payload) && (encoded_size += PB._encoded_size(x.original_payload, 21))
    !isempty(x.attribute_indices) && (encoded_size += PB._encoded_size(x.attribute_indices, 22))
    return encoded_size
end

struct ScopeProfiles <: AbstractProtoBufMessage
    scope::Union{Nothing,opentelemetry.proto.common.v1.InstrumentationScope}
    profiles::Vector{Profile}
    schema_url::String
end
PB.default_values(::Type{ScopeProfiles}) = (;scope = nothing, profiles = Vector{Profile}(), schema_url = "")
PB.field_numbers(::Type{ScopeProfiles}) = (;scope = 1, profiles = 2, schema_url = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ScopeProfiles})
    scope = Ref{Union{Nothing,opentelemetry.proto.common.v1.InstrumentationScope}}(nothing)
    profiles = PB.BufferedVector{Profile}()
    schema_url = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, scope)
        elseif field_number == 2
            PB.decode!(d, profiles)
        elseif field_number == 3
            schema_url = PB.decode(d, String)
        else
            PB.skip(d, wire_type)
        end
    end
    return ScopeProfiles(scope[], profiles[], schema_url)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ScopeProfiles)
    initpos = position(e.io)
    !isnothing(x.scope) && PB.encode(e, 1, x.scope)
    !isempty(x.profiles) && PB.encode(e, 2, x.profiles)
    !isempty(x.schema_url) && PB.encode(e, 3, x.schema_url)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ScopeProfiles)
    encoded_size = 0
    !isnothing(x.scope) && (encoded_size += PB._encoded_size(x.scope, 1))
    !isempty(x.profiles) && (encoded_size += PB._encoded_size(x.profiles, 2))
    !isempty(x.schema_url) && (encoded_size += PB._encoded_size(x.schema_url, 3))
    return encoded_size
end

struct ResourceProfiles <: AbstractProtoBufMessage
    resource::Union{Nothing,opentelemetry.proto.resource.v1.Resource}
    scope_profiles::Vector{ScopeProfiles}
    schema_url::String
end
PB.reserved_fields(::Type{ResourceProfiles}) = (names = String[], numbers = Union{Int,UnitRange{Int}}[1000])
PB.default_values(::Type{ResourceProfiles}) = (;resource = nothing, scope_profiles = Vector{ScopeProfiles}(), schema_url = "")
PB.field_numbers(::Type{ResourceProfiles}) = (;resource = 1, scope_profiles = 2, schema_url = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResourceProfiles})
    resource = Ref{Union{Nothing,opentelemetry.proto.resource.v1.Resource}}(nothing)
    scope_profiles = PB.BufferedVector{ScopeProfiles}()
    schema_url = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, resource)
        elseif field_number == 2
            PB.decode!(d, scope_profiles)
        elseif field_number == 3
            schema_url = PB.decode(d, String)
        else
            PB.skip(d, wire_type)
        end
    end
    return ResourceProfiles(resource[], scope_profiles[], schema_url)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResourceProfiles)
    initpos = position(e.io)
    !isnothing(x.resource) && PB.encode(e, 1, x.resource)
    !isempty(x.scope_profiles) && PB.encode(e, 2, x.scope_profiles)
    !isempty(x.schema_url) && PB.encode(e, 3, x.schema_url)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResourceProfiles)
    encoded_size = 0
    !isnothing(x.resource) && (encoded_size += PB._encoded_size(x.resource, 1))
    !isempty(x.scope_profiles) && (encoded_size += PB._encoded_size(x.scope_profiles, 2))
    !isempty(x.schema_url) && (encoded_size += PB._encoded_size(x.schema_url, 3))
    return encoded_size
end

struct ProfilesData <: AbstractProtoBufMessage
    resource_profiles::Vector{ResourceProfiles}
end
PB.default_values(::Type{ProfilesData}) = (;resource_profiles = Vector{ResourceProfiles}())
PB.field_numbers(::Type{ProfilesData}) = (;resource_profiles = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ProfilesData})
    resource_profiles = PB.BufferedVector{ResourceProfiles}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, resource_profiles)
        else
            PB.skip(d, wire_type)
        end
    end
    return ProfilesData(resource_profiles[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ProfilesData)
    initpos = position(e.io)
    !isempty(x.resource_profiles) && PB.encode(e, 1, x.resource_profiles)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ProfilesData)
    encoded_size = 0
    !isempty(x.resource_profiles) && (encoded_size += PB._encoded_size(x.resource_profiles, 1))
    return encoded_size
end
