name = "OpenTelemetryProto"
uuid = "cc651e92-2989-4f95-bcc3-32e6fb6ac025"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.20.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
ProtoBuf = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
